apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      volumes:
        - name: aws
          secret:
            secretName: aws-secret
            optional: false
      containers:
        - name: udagram-api-user
          image: ereyomi/udagram-api-user
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          volumeMounts:
            - name: aws
              mountPath: '/root/.aws'
              readOnly: true
          envFrom:
            - secretRef:
                name: app-secret
            - configMapRef:
                name: app-config
      restartPolicy: Always
