services:
  - docker

before_script:
  - docker-compose -f docker-compose-build.yaml build --parallel

script:
  # Tagging
  - docker tag reverseproxy triple0t/reverseproxy:latest
  - docker tag udagram-api-feed triple0t/udagram-api-feed:latest
  - docker tag udagram-api-user triple0t/udagram-api-user:latest
  - docker tag udagram-frontend triple0t/udagram-frontend:latest
  # Pushing
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push triple0t/reverseproxy:latest
  - docker push triple0t/udagram-api-feed:latest
  - docker push triple0t/udagram-api-user:latest
  - docker push triple0t/udagram-frontend:latest
