apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-feed
  template:
    metadata:
      labels:
        app: backend-feed
    spec:
      volumes:
        - name: aws
          secret:
            secretName: aws-secret
            optional: false
      containers:
        - name: backend-feed
          image: ereyomi/udagram-api-feed:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          volumeMounts:
            - name: aws
              mountPath: '/root/.aws'
              readOnly: true
          envFrom:
            - secretRef:
                name: udagram-db-secrets
            - configMapRef:
                name: udagram-env
      restartPolicy: Always
